# Generated by Django 6.0.4 on 2026-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'verbose_name': 'Professional Profile', 'verbose_name_plural': 'Professional Profiles'},
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='speciality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lawyer', 'Lawyer'), ('orientation', 'Academic Advisor'), ('housing', 'Landlord / Agency'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
