# Generated by Django 6.0.4 on 2026-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_professionalprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='True only after admin validation for professional accounts'),
        ),
    ]
