# Generated by Django 6.0.4 on 2026-05-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Chat Group', 'verbose_name_plural': 'Chat Groups'},
        ),
    ]
