# Generated by Django 6.0.4 on 2026-04-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('chambre', 'Chambre'), ('appartement', 'Appartement'), ('colocation', 'Colocation')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce de logement',
                'verbose_name_plural': 'Annonces de logement',
                'ordering': ['-created_at'],
            },
        ),
    ]
