# Generated by Django 6.0.4 on 2026-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
