# Generated by Django 6.0.4 on 2026-04-26 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_housinglisting_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housinglisting',
            name='photos',
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='type',
            field=models.CharField(choices=[('chambre', 'Room'), ('appartement', 'Apartment'), ('colocation', 'Shared housing')], max_length=20),
        ),
    ]
