# Generated by Django 6.0.4 on 2026-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_housinglisting_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', verbose_name='Photo'),
        ),
    ]
