# Generated by Django 6.0.4 on 2026-05-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_housinglisting_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housinglisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Housing Listing', 'verbose_name_plural': 'Housing Listings'},
        ),
    ]
